export enum AuthorizeActionType {
    
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    SIGNUP = 'SIGNUP',
    UPDATE_PASSWORD = 'UPDATE_PASSWORD',
    DB_FETCH_USER_PRIVILEGED = 'DB_FETCH_USER_PRIVILEGED',
    DB_FETCH_USER_ACTIVITIES = 'DB_FETCH_USER_ACTIVITIES',
}
